### ISSUE TITLE
support `meta` block in workflow body as well as task

### ISSUE THREAD

**Issue by delocalizer** [broadinstitute/wdl#67]
The grammar currently only allows `meta` in tasks. We'd love to be able to explicitly track versioning & provenance of workflows themselves by embedding some identifiers in a workflow-level meta block, something like the following:

```
...
workflow finishQuickly {
  meta {
    revision: "1.0.0"
    url: "https://path/to/my/repo/finishQuickly.wdl" 
  }
  call Usain
}
```

**Comment by geoffjentry** [comment]
This is interesting, I didn't know anyone ws using the `meta` block, I'm glad it gets some love.

@kcibul I suspect this should be a super easy change

**Comment by patmagee** [comment]
I +1 this and would love if it was extended to the `parameter_meta` as well. We were thinking that we may have to parse comments to attain this information, but if these blocks are implemented it would greatly be appreciated

**Comment by geoffjentry** [comment]
@delocalizer @patmagee I put together a quick PR on wdl4s to take care of this. Once it's in I'll update cromwell & wdltool so it'll be live. It turned out I was wrong in that the scala objects *were* aware of these blocks but it doesn't exit wdl4s so the other software only needs to update their dependency.

**Comment by delocalizer** [comment]
thanks @geoffjentry, closed by https://github.com/broadinstitute/wdl4s/pull/53
